version: '3'

services:
  postgres:
    image: 'kartoza/postgis'
    volumes:
      - 'postgres:/var/lib/postgres/data'
    ports:
      - '5432:5432'

  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    ports: 
      - '3000:3000'
    volumes:
      - '.:/app'
      - 'gems:/gems'

volumes:
  postgres:
  gems: